# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mariadb
    ports:
      - "3306:3306"
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
